### ISSUE TITLE
Resetting state breaks tracking later on, leading to segfaults

### ISSUE THREAD

**Issue by itamarst** [pythonspeed/filprofiler#108]
Originally discovered due to failing test on on macOS + Python 3.9:
```
    def test_no_profiling():
        """Neither memory tracking nor Python profiling happen by default."""
        address = pymalloc(365)
        # No information about size available, since it's not tracked:
>       assert preload.pymemprofile_get_allocation_size(c_void_p(address)) == 0
E       AssertionError: assert 496 == 0
E        +  where 496 = <_FuncPtr object at 0x7f86dd5fed80>(c_void_p(140217251802320))
E        +    where <_FuncPtr object at 0x7f86dd5fed80> = <PyDLL '/Users/runner/work/filprofiler/filprofiler/filprofiler/_filpreload.cpython-39-darwin.so', handle 112c35660 at 0x7f86dd59f2b0>.pymemprofile_get_allocation_size
E        +    and   c_void_p(140217251802320) = c_void_p(140217251802320)
```

**Comment by itamarst** [comment]
The above was because stopping tracking doesn't clear allocations, which it probably should.

After a bit of investigation, got a coredump which suggests a more fundamental bug: clearing allocations makes the allocation state and thread-local state are out of sync, which leads to panics.

```
#0  0x00007f42d367c9d5 in raise () from /lib64/libc.so.6                                                                                                                                      #1  <signal handler called>                                                                                                                                                                   #2  0x00007f42d367c9d5 in raise () from /lib64/libc.so.6                                                                                                                                      #3  0x00007f42d36658a4 in abort () from /lib64/libc.so.6                                                                                                                                      #4  0x00007f42d3bc1187 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:167                                                                                            #5  0x00007f42d3bc1175 in std::sys_common::util::abort () at library/std/src/sys_common/util.rs:19                                                                                            #6  0x00007f42d3bc111d in std::panicking::rust_panic () at library/std/src/panicking.rs:620                                                                                                   #7  0x00007f42d3bc0ca5 in std::panicking::rust_panic_with_hook () at library/std/src/panicking.rs:588                                                                                         #8  0x00007f42d3b84cf3 in std::panicking::begin_panic::{{closure}} () from /home/itamarst/Devel/memory-profiler/filprofiler/_filpreload.cpython-38-x86_64-linux-gnu.so                        #9  0x00007f42d3b8435c in std::sys_common::backtrace::__rust_end_short_backtrace () from /home/itamarst/Devel/memory-profiler/filprofiler/_filpreload.cpython-38-x86_64-linux-gnu.so          #10 0x00007f42d3b84cca in std::panicking::begin_panic () from /home/itamarst/Devel/memory-profiler/filprofiler/_filpreload.cpython-38-x86_64-linux-gnu.so                                     #11 0x00007f42d3bb604d in <im::vector::Vector<A> as core::ops::index::IndexMut<usize>>::index_mut ()                                                                                             from /home/itamarst/Devel/memory-profiler/filprofiler/_filpreload.cpython-38-x86_64-linux-gnu.so                                                                                           #12 0x00007f42d3badc56 in pymemprofile_api::memorytracking::add_allocation () from /home/itamarst/Devel/memory-profiler/filprofiler/_filpreload.cpython-38-x86_64-linux-gnu.so                #13 0x00007f42d3b83dbd in add_allocation (size=28, address=139924590936064) at filprofiler/_filpreload.c:286                                                                                  #14 malloc (size=28) at filprofiler/_filpreload.c:304                                                                                                                                         #15 0x00007f42d39080b3 in _PyLong_New () from /lib64/libpython3.8.so.1.0
```

Basically per-thread tracking assumes the allocations-per-callstack-id vector is the right length... but it isn't if we've done a reset.
